### ISSUE TITLE
Use first frame from GIF instead last one

### ISSUE THREAD

**Issue by gomax** [leafo/magick#22]
I have problem with GIF thumbnailing. Now 'magick' use static image as thumbnail for gif, ok. But it takes the last frame, and sometimes its broken.

There are 2 attached files. The first one is a screenshot of the original last frame and theresult. The second attach is original gif file.
![git_thumb](https://cloud.githubusercontent.com/assets/530506/10165490/4f71a79a-66c8-11e5-9586-a7fe86cc2c5c.png)
![064ff87673c5ae3dc26fbaacfb722d32](https://cloud.githubusercontent.com/assets/530506/10165498/56412a50-66c8-11e5-86e6-febb4ab5083d.gif)

**Comment by antonrubtsov** [comment]
+1

**Comment by karai17** [comment]
+1

**Comment by leafo** [comment]
the coalesce method now exists, but I don't recommend it if you're using it for user uploaded image. It's going to use up a lot of memory, and potentially be an attack vector. I created this library to hande extracting the first frame from a gif: https://github.com/leafo/giflib
