### ISSUE TITLE
Can't find magick on luarocks

### ISSUE THREAD

**Issue by booyaa** [leafo/magick#29]
Sample output from `luarocks search -all`can be found this [gist](https://gist.github.com/booyaa/feed8fa2904da6571ab9)

using LuaRocks 2.2.2 on OSX (installed via lua homebrew package)

**Comment by leafo** [comment]
Since magick is only for luajit, it only shows up for luarocks running lua 5.1. Chances are you're luarocks is set up for a newer version of lua.

**Comment by booyaa** [comment]
Cheers, I'll downgrade!

On Thursday, 10 December 2015, leaf <notifications@github.com> wrote:

> Since magick is only for luajit, it only shows up for luarocks running lua
> 5.1. Chances are you're luarocks is set up for a newer version of lua.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leafo/magick/issues/29#issuecomment-163710333>.
>


-- 
Sent from Gmail BatMobile

**Comment by Velrok** [comment]
```
❯ brew install lua51
Warning: Formula lua51 was renamed to lua@5.1.
Error: lua@5.1 has been disabled because it is deprecated upstream!
```

😢 Any chance of getting support for newer lua versions?

**Comment by TamaMcGlinn** [comment]
On Ubuntu 20.04 and 22.04 I ran into the same issue:

```
$ sudo luarocks install magick

Error: No results matching query were found for Lua 5.3.
```

But trying to install for 5.1 also fails

```
$ sudo luarocks install --lua-version=5.1 magick
Warning: Lua 5.1 interpreter not found at /usr

Modules may not install with the correct configurations. You may want to configure the path prefix to your build of Lua 5.1 using

   luarocks config --local lua_dir <your-lua-prefix>

Installing https://luarocks.org/magick-1.6.0-1.src.rock

Error: Failed finding Lua header files. You may need to install them or configure LUA_INCDIR.
```

The solution:
```
sudo apt install lua5.1
luarocks install --lua-version=5.1 magick
```

Note no sudo on the final luarocks install.
