### ISSUE TITLE
signal 17 (SIGCHLD) received

### ISSUE THREAD

**Issue by YadrovSergey** [leafo/magick#35]
When i add line to code

`local magick = require("magick")`

nginx log say:

2016/06/29 14:10:38 [info] 5#0: waitpid() failed (10: No child processes)
2016/06/29 14:10:39 [notice] 5#0: signal 17 (SIGCHLD) received

It is normal?

**Comment by wotek** [comment]
@YadrovSergey what was it? I keep getting this as well but so far magick works.
