### ISSUE TITLE
module 'magick' not found.

### ISSUE THREAD

**Issue by rpatelob** [leafo/magick#43]
I have installed magick but when I try to access it, it gives me an error says magick not found.

2017/03/09 10:57:15 [error] 27432#0: *1 lua entry thread aborted: runtime error: ...tml/default/image-server-tutorial/magick-master/test.lua:1: module 'magick' not found:
	no field package.preload['magick']
	no file '/usr/local/openresty/site/lualib/magick.lua'
	no file '/usr/local/openresty/site/lualib/magick/init.lua'
	no file '/usr/local/openresty/lualib/magick.lua'
	no file '/usr/local/openresty/lualib/magick/init.lua'
	no file './magick.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/magick.lua'
	no file '/usr/local/share/lua/5.1/magick.lua'
	no file '/usr/local/share/lua/5.1/magick/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/magick.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/magick/init.lua'
	no file '/usr/local/openresty/site/lualib/magick.so'
	no file '/usr/local/openresty/lualib/magick.so'
	no file './magick.so'
	no file '/usr/local/lib/lua/5.1/magick.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/magick.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

above is my output. And when I checked "whereis magick", it gives me "magick: /usr/local/bin/magick".

**Comment by leafo** [comment]
how did you install it? The error message is saying that it can't find it in any of the paths listed, so maybe you need to update your `package.path`

**Comment by rpatelob** [comment]
I followed the installation steps given in this repo. And how do I change package.path?

**Comment by rpatelob** [comment]
When I ran `luarocks list`, it shows `Installed rocks:
magick
   1.2.1-1 (installed) - /usr/local/lib/luarocks/rocks-5.1`

**Comment by rpatelob** [comment]
Finally, I have successfully installed magick, but now again a new error.
It says `runtime error: /usr/local/share/lua/5.1/magick/wand/image.lua:95: Failed to load filter list, can't resize`

**Comment by kobzar** [comment]
The same issue

**Comment by rpatelob** [comment]
I had fixed it. I made a mistake in installation.

**Comment by kobzar** [comment]
but how i can check it? in luarocks the same version. I reinstalled the library - but issue is still present.
